In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.1.0'

In [3]:
df = pd.read_csv('housing.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [4]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [5]:
df.ocean_proximity.nunique()

5

In [6]:
df[df.ocean_proximity == 'NEAR BAY'].median_house_value.mean()

259212.31179039303

In [7]:
total_bedrooms_mean = df.total_bedrooms.mean()
total_bedrooms_mean

537.8705525375618

In [8]:
df = df.fillna(total_bedrooms_mean)

In [9]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [10]:
df.total_bedrooms.mean()

537.8705525375617

In [11]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [23]:
X = df[df.ocean_proximity == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']].to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [24]:
XT = X.T
XT

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [36]:
XTX = XT @ X
XTX.round(2)

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [37]:
XTXinv = np.linalg.inv(XTX)

In [38]:
I = XTXinv @ XTX
I.round(2)

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [39]:
y = [950, 1300, 800, 1000, 1300]

In [40]:
w = XTXinv @ XT @ y
w

array([23.12330961, -1.48124183,  5.69922946])